{% set version = "1.0.1" %}

package:
  name: lilly-medchem-rules
  version: {{ version }}

source:
  url: https://github.com/hadim/Lilly-Medchem-Rules/archive/refs/tags/{{ version }}.tar.gz
  sha256: b7783607ffc1aa33c136404d928a3f05a39378eeff164bf0cd86dcdd8b8e908a

  patches:
    - compile.patch

build:
  number: 1
  skip : true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                    # [unix]
    - ninja                   # [win]
    - zlib                    # [build_platform != target_platform]
  host:
    - zlib

test:
  commands:
    - test -f "${PREFIX}/bin/iwdemerit"           # [unix]
    - test -f "${PREFIX}/bin/mc_first_pass"       # [unix]
    - test -f "${PREFIX}/bin/mc_summarise"        # [unix]
    - test -f "${PREFIX}/bin/tsubstructure"       # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\iwdemerit.exe" exit 1       # [win]
    - if not exist %LIBRARY_PREFIX%\bin\mc_first_pass.exe" exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\bin\mc_summarise.exe" exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\bin\tsubstructure.exe" exit 1   # [win]

about:
  home: https://github.com/IanAWatson/Lilly-Medchem-Rules
  summary: 'Implementation of Lilly Medchem Rules - J Med Chem 2012'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
